version: '3'

services:

  nginx:
    restart: always
    image: nginx:1.20
    ports:
      - "${APP_EXTERNAL_PORT}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx

  php:
    restart: always
    build: ./docker/php-fpm
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - nginx
      - redis

  db:
    restart: always
    image: postgres:13
    ports:
       - "${DB_EXTERNAL_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:6.2

volumes:
  db_data: {}
